# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: auth-server
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  timeout: 60 # optional, in seconds, default is 6
  apiGateway:
    shouldStartNameWithService: true
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors: false
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: false
